feat: implement hot swap on deploy

diff --git a/.github/workflows/deploy-to-staging.yml b/.github/workflows/deploy-to-staging.yml
--- a/.github/workflows/deploy-to-staging.yml
+++ b/.github/workflows/deploy-to-staging.yml
@@ -20,6 +20,10 @@ jobs:
         name: FTP-Deploy-Action
         runs-on: ubuntu-latest
         needs: [Linting]
+        env:
+          PLUGIN_DEST: /htdocs/wp-content/plugins/custom-plugin
+          PLUGIN_SOURCE: /htdocs/wp-content/uploads/custom-plugin__new
+          PLUGIN_BACKUP: /htdocs/wp-content/plugins/custom-plugin__bak
         if: ${{ vars.STAGING_SITES != '' }}
         strategy:
             matrix:
@@ -52,10 +56,40 @@ jobs:
             - name: Install Composer dependencies
               run: composer install --no-dev --optimize-autoloader
 
-            - name: FTP-Deploy-Action to Staging Site ${{ matrix.site_name }}
+            - name: Ensure remote directory exists
+              run: |
+                sudo apt-get update -qq && sudo apt-get install -y -qq lftp
+                lftp -c "
+                  set sftp:connect-program 'ssh -o StrictHostKeyChecking=no'
+                  set cmd:interactive no
+                  open -u ${{ secrets[format('STAGING_SFTP_USER_{0}', matrix.site_name)] }},${{ secrets[format('STAGING_SFTP_PASSWORD_{0}', matrix.site_name)] }} sftp://sftp.wp.com
+                  cd /htdocs/wp-content/uploads
+                  mkdir custom-plugin__new
+                  quit
+                "
+
+            - name: FTP-Deploy-Action to a new folder ${{ matrix.site_name }}
               uses: Automattic/FTP-Deploy-Action@3.1.2
               with:
-                  ftp-server: sftp://sftp.wp.com/htdocs/wp-content/plugins/custom-plugin/
+                  ftp-server: sftp://sftp.wp.com${{ env.PLUGIN_SOURCE }}
                   ftp-username: ${{ secrets[format('STAGING_SFTP_USER_{0}', matrix.site_name)] }}
                   ftp-password: ${{ secrets[format('STAGING_SFTP_PASSWORD_{0}', matrix.site_name)] }}
                   git-ftp-args: --insecure
+
+            - name: Atomic swap directories
+              run: |
+                sudo apt-get update -qq && sudo apt-get install -y -qq lftp
+                LFTP_OPEN="set sftp:connect-program 'ssh -o StrictHostKeyChecking=no'; set cmd:interactive no; open -u ${{ secrets[format('STAGING_SFTP_USER_{0}', matrix.site_name)] }},${{ secrets[format('STAGING_SFTP_PASSWORD_{0}', matrix.site_name)] }} sftp://sftp.wp.com"
+                # Move existing plugin to backup (no-op on first deploy)
+                lftp -c "$LFTP_OPEN; mv $PLUGIN_DEST $PLUGIN_BACKUP; quit" || true
+                # Copy uploads dir to plugin dir via runner (mv often fails across remote dirs on SFTP)
+                lftp -c "
+                  $LFTP_OPEN
+                  lcd /tmp
+                  mirror $PLUGIN_SOURCE plugin-deploy
+                  mirror -R plugin-deploy $PLUGIN_DEST
+                  rm -rf $PLUGIN_SOURCE
+                  quit
+                "
+                # Remove backup (ignore error)
+                lftp -c "$LFTP_OPEN; rm -rf $PLUGIN_BACKUP; quit" || true
